let buttons = document.querySelector("#rsvpButton")

let rsvpCase = [
    {case: "0", message: ''},
    {case: "1", message: '<b>Please click the link to rsvp yourself!</b>'},
    {case: "2", message: '<b>Please click the link to rsvp you and your plus one if you have one!</b>'},
    {case: "3", message: '<b>Please click the link to rsvp you and your family!</b>'},
    {case: "4", message: '<b>Please click the link to rsvp!</b>'},
    {case: "5", message: '<b>Please click the link to rsvp you and your spouse!</b>'},

];
let guestList = [
    {name: "ryan dunton", rsvp: 4},
    {name: "cici holmquist", rsvp: 1},
    {name: "scott tintes", rsvp: 5},
    {name: "brandi tintes", rsvp: 5},
    {name: "corey vahlbusch", rsvp: 4},
    {name: "jadan tish", rsvp: 5},
    {name: "paige tish", rsvp: 5},
    {name: "josh petersen", rsvp: 2},
    {name: "caleb meger", rsvp: 4},
    {name: "abigail lester", rsvp:"" },
    {name: "bob bitgood", rsvp: 1},
    {name: "don lester", rsvp: 5},
    {name: "brent lester", rsvp: 3},
    {name: "charlotte lester", rsvp: 3},
    {name: "caitlyn lester", rsvp: 2},
    {name: "stephanie lester", rsvp: 2},
    {name: "wil lester", rsvp: 2},
    {name: "jake lester", rsvp: 3},
    {name: "christina lester", rsvp: 3},
    {name: "steve lester", rsvp: 3},
    {name: "tamma lester", rsvp: 3},
    {name: "anna evans", rsvp: 3},
    {name: "dustin evans", rsvp: 3},
    {name: "laura lester", rsvp: 1},
    {name: "elizabeth lester", rsvp: 1},
    {name: "sarah arnold", rsvp: 1},
    {name: "jim abeyta", rsvp: ""},
    {name: "lori abeyta", rsvp: ""},
    {name: "marcia amundson", rsvp: ""},
    {name: "amundson", rsvp: ""},
    {name: "nathan benson", rsvp: ""},
    {name: "steven chafer", rsvp: 5},
    {name: "tammi chafer", rsvp: 5},
    {name: "mike coady", rsvp: ""},
    {name: "terri coady", rsvp: ""},
    {name: "hannah coady", rsvp: ""},
    {name: "jamie coder", rsvp: ""},
    {name: "ralph coder", rsvp: ""},
    {name: "robert coder", rsvp: ""},
    {name: "zoe coder", rsvp: ""},
    {name: "samantha fisher", rsvp: ""},
    {name: "jay fisher", rsvp: ""},
    {name: "jamie fisher", rsvp: ""},
    {name: "ben fisher", rsvp: ""},
    {name: "todd flicek", rsvp: ""},
    {name: "jalene flicek", rsvp: ""},
    {name: "piper flicek", rsvp: ""},
    {name: "titus flicek", rsvp: ""},
    {name: "mike hadden", rsvp: ""},
    {name: "gretchen hadden", rsvp: ""},
    {name: "olivia hadden", rsvp: ""},
    {name: "jackson hadden", rsvp: ""},
    {name: "helgerson", rsvp: ""},
    {name: "helgerson", rsvp: ""},
    {name: "andrea helgerson", rsvp: ""},
    {name: "adam helgerson", rsvp: ""},
    {name: "robby kay", rsvp: ""},
    {name: "lori kay", rsvp: ""},
    {name: "jacob klinkner", rsvp: 2},
    {name: "corey kohnen", rsvp: ""},
    {name: "heather kohnen", rsvp: ""},
    {name: "hannah kohnen", rsvp: ""},
    {name: "josh kohnen", rsvp: ""},
    {name: "jenny kuklok", rsvp: ""},
    {name: "doug kuklok", rsvp: ""},
    {name: "lily kuklok", rsvp: ""},
    {name: "josh lieder", rsvp: ""},
    {name: "sarah lieder", rsvp: ""},
    {name: "abby meyer", rsvp: ""},
    {name: "dee norling", rsvp: ""},
    {name: "lanae olson", rsvp: 2},
    {name: "amber pogreba", rsvp: 2},
    {name: "wayne sanders", rsvp: ""},
    {name: "bonita sanders", rsvp: ""},
    {name: "pete stadem", rsvp: ""},
    {name: "kari stadem", rsvp: ""},
    {name: "peggy thompson", rsvp: ""},
    {name: "ted thompson", rsvp: ""},
    {name: "david twite", rsvp: ""},
    {name: "tracy twite", rsvp: ""},
    {name: "jr vandyken", rsvp: ""},
    {name: "andi vandyken", rsvp: ""},
    {name: "lindsey vo", rsvp: ""},
    {name: "michael vo", rsvp: ""},
    {name: "kathy webb", rsvp: ""},
    {name: "clay webb", rsvp: ""},
    {name: "kymberly west", rsvp: ""},
    {name: "clint west", rsvp: ""},
    {name: "sue williamson", rsvp: ""}, 
    {name: "randy williamson", rsvp: ""},
    {name: "kari winkler", rsvp: ""},
    {name: "gerard winkler", rsvp: ""},
    {name: "evan winkler", rsvp: ""},
    {name: "mike mesmer", rsvp: ""},
    {name: "sarah mesmer", rsvp: ""},
    {name: "marykay lind", rsvp: ""},
    {name: "gary lind", rsvp: ""},
    {name: "kelly johnston", rsvp: ""},
    {name: "charles johnston", rsvp: ""},   
    {name: "chuck keane", rsvp: ""},
    {name: "heather keane", rsvp: ""},
    {name: "catie anthony", rsvp: 2},
    {name: "dale bloemke", rsvp: 4},
    {name: "lisa bloemke", rsvp: 2},
    {name: "donny bloemke", rsvp: 5},
    {name: "sheri bloemke", rsvp: 5},
    {name: "jeff kopseng", rsvp: 3},
    {name: "alan bloemke", rsvp: 3},
    {name: "justin bloemke", rsvp: 2},  
    {name: "brock bloemke", rsvp: 5},
    {name: "jody bloemke", rsvp: ""},
    {name: "bruno drews", rsvp: 4},
    {name: "bob fischer", rsvp: 5},
    {name: "marie fischer", rsvp: 5},
    {name: "ron konz", rsvp: 5},
    {name: "ann konz", rsvp: 5},
    {name: "kay ludewig", rsvp: 5},
    {name: "eugine ludewig", rsvp: 5},
    {name: "ruthanne miller", rsvp: 5},
    {name: "dave miller", rsvp: 5},
    {name: "leah miller", rsvp: 4},
    {name: "brian miller", rsvp: 5},
    {name: "jenny miller", rsvp: 5},
    {name: "nancy nachreiner", rsvp: 3},
    {name: "linda nelson", rsvp: 5},
    {name: "lee nelson", rsvp: 5},
    {name: "melissa roiger", rsvp: 3},
    {name: "brandon roiger", rsvp: 3},
    {name: "alexia roiger", rsvp: 2},
    {name: "ed schottenbauer", rsvp: ""},
    {name: "pearl schottenbauer", rsvp: ""},
    {name: "suzanne wels", rsvp: 3},
    {name: "brian wels", rsvp: 3},
    {name: "racheal crissinger", rsvp: 2},
    {name: "greg curtis", rsvp: 5},
    {name: "trisha curtis", rsvp: 5},
    {name: "chrissy dunton", rsvp: 3},
    {name: "chris dunton", rsvp: 3},
    {name: "chad olthoff", rsvp: 3},
    {name: "levi rainwater", rsvp: 2},
    {name: "shari winkelmann", rsvp: 5},
    {name: "dean winklemann", rsvp: 5},
    {name: "clint imker", rsvp: 5},
    {name: "kaci imker", rsvp: 5},
    {name: "maddy leinen", rsvp: 5},
    {name: "brandon marks", rsvp: 5},
    {name: "sadie marks", rsvp: 5},
    {name: "adam leinen", rsvp: 5},
    {name: "hali winkelmann", rsvp: 2},
    {name: "russ anderson", rsvp: 5},
    {name: "kim anderson", rsvp: 5},
    {name: "", rsvp: ""},
]

buttons.onclick = function test() {
    let fName = (document.getElementById("fullName").value).toLowerCase()
    let nameCheck = guestList.find((person) => person.name === fName)
    let answer =""
    if (nameCheck.rsvp) {
        answer = "Yes!"
        document.getElementById("rsvpBody").style.display = "block"
    } else {
        answer = "That name is not on the list!"
    }
    document.getElementById("results").innerHTML = rsvpCase[nameCheck.rsvp].message
}